apiVersion: v1
kind: Service
metadata:
  name: micro-frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: micro-frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}